### PR TITLE
Fix install of python package

### PR DESCRIPTION
**Pull request by ftalbrecht**
This requires https://github.com/dune-community/dune-pybindxi/pull/7

### CODE REVIEW

**Comment by ftalbrecht** [comment]
Just restarting the travis builds does not make them pass (I was hoping the docker images would contain the updated dune-pybindxi by now). Any ideas, @renefritze?

**Comment by renefritze** [comment]
DId you bump the pybind module in the super module?

**Comment by ftalbrecht** [comment]
On Mon, 2019-01-07 at 23:52 -0800, René Fritze wrote:
> DId you bump the pybind module in the super module?

What, this is not happening automatically? :)

Thx for the hint, I'll try again...

**Comment by renefritze** [comment]
https://github.com/dune-community/dune-pybindxi/pull/7#issuecomment-447494536 wrote:
> You need to merge this PR and/or update the ref in the super module before your downstream PRs can begin to succeed. Otherwise the docker images still have the old version of this module.

I guess _technically_ you followed that :wink:

**Pull request merged**
