### PR TITLE
Storage provider bugfix

### PR DESCRIPTION
**Pull request by renemilk**
The important commit is 
d81258a955a9175133c9bcc4b1dd1009461752f9

I'll be adding to this PR a little more.

### CODE REVIEW

**Comment by renemilk** [comment]
Looking at extending the tests, I think we @dune-community/dune-xt-common-devs  first need to clarify what the StorageProvider actually is supposed to do. Is it supposed to copy its input? Why is there both ```storage_access``` and the equivalent ```access```? Is it intentional that the move/copy assignment ops are deleted, but the ctors are defaulted?

I had assumed that it should not copy its input since there's only a ctor to move unique ptrs into it.

**Comment by ftalbrecht** [comment]
The `storage_access` methods should have been dropped, my fault.

**Comment by ftalbrecht** [comment]
As discussed, the desired behaviour is that you loose ownership of raw pointers. I will update the test and document the desired API.

**Comment by ftalbrecht** [comment]
Once travis is happy, so am I.

**Comment by renemilk** [comment]
The failed check was due to apt-get outage. Re-running now and closing/merging afterwards.

**Pull request merged**
