### PR TITLE
[ci] Set up CI with Azure Pipelines

### PR DESCRIPTION
**Pull request by renefritze**

### CODE REVIEW

**Comment by renefritze** [comment]
Turns out if I hadn't been stupidly trying to use the wrong codecov token for a while the move would have been super simple :smile: 

My plan now is to move all the xt modules' CI to azure and remove the binning setup. Azure allows 6h runtime for each pipeline, with 4 pipelines max concurrently. 

For dune-gdt I'm still planning to move to gitlab-ci via a mirror on zivgitlab since it most benefits from the faster build machine.

**Comment by tobiasleibner** [comment]
Very nice!

**Comment by renefritze** [comment]
I'm also now finally able to get rid of the complex script update mechanism from the super module. There's now a common submodule in `.ci/shared` in each xt module and azure is actually able to take a job template from the repo prior to executing the actual pipeline. 

Once the the PR here is green for azure I'll be removing the branch protection requirement on travis and add azure instead. Btw, @dune-community/dune-xt-devs should be able to restart jobs on the "checks" tab in PRs w/o needing an azure login.

**Comment by renefritze** [comment]
FYI: Ever since https://github.com/dune-community/dune-xt-common/commit/44b97d13f7bf3aeab4a4cb015d3f33afd64f4db4#diff-e66b349be7537712972ad4c1eb2b3daeR279 no python tests in either xt module have been executed. dune-common now provides a `test_python` target which we did not hook into other than compiling bindings. 
I've now added a `xt_test_python` target and made `test_python` depend on it so no scripts will break

**Pull request merged**
