### PR TITLE
Refactor convergence study

### PR DESCRIPTION
**Pull request by ftalbrecht**
This pr refactors the convergence study to match the new dune-gdt.
I do not think that we use it anywhere else, but merging this pr will break the old dune-gdt tests, so perhaps we postpone this a bit ...

### CODE REVIEW

**Comment by ftalbrecht** [comment]
Yeah, this is bothering me for quite some time now, and I could not really decide. So you prefer to leave out the else if there is a return in the if? I think I could live well with that...

**Comment by tobiasleibner** [comment]
+1 for leaving out the else.

**Comment by tobiasleibner** [comment]
If this breaks the old dune-gdt, we can just wait until we switched to the new-master. Depends on: #135 .

**Comment by renefritze** [comment]
Reminder: fixing that conflict can [[skip ci]](https://docs.travis-ci.com/user/customizing-the-build/#skipping-a-build)

**Pull request merged**
