### PR TITLE
[lapacke] drop cblas

### PR DESCRIPTION
**Pull request by ftalbrecht**
This is not meant to be merged directly.

On SYAL, `HAVE_MKL || HAVE_CBLAS` is true, but the wrapper do not compile since `CBLAS_UPLO` etc. are undefined. Defining the corresponding enums manually yields other errors, as the `clas` functions expect different arguments.

Bottom line: we need better/more portable wrappers :/ Any ideas, @tobiasleibner ?

In addition: I would like to see those in `dune/xt/common/cblas.{cc,hh}` and the `exp` in `dune/xt/common/mkl.{cc, hh}`.

### CODE REVIEW

**Comment by tobiasleibner** [comment]
``MKL`` includes cblas and defines ``CBLAS_UPLO``, so I thought this should not happen. Maybe ``MKL`` can be built without ``cblas``? Then we should probably check for something like
```
HAVE_MKL_CBLAS || HAVE_CBLAS
```

**Comment by tobiasleibner** [comment]
The problem is due to an old cblas version, see https://github.com/xianyi/OpenBLAS/issues/1754. Adding
```
typedef CBLAS_ORDER CBLAS_LAYOUT;
```
fixes compilation on Syal. I am not sure how we can fix this in general, probably we would have to filter out incompatible cblas versions. 
The easy fix would be to remove support for any cblas expect MKL, so we would only check for ``HAVE_MKL``. For me that would be fine.

**Comment by ftalbrecht** [comment]
> The easy fix would be to remove support for any cblas expect MKL, so we would only check for `HAVE_MKL`. For me that would be fine.

Me too. I will prepare something ...

**Comment by ftalbrecht** [comment]
Please have a look, @tobiasleibner. I also did some renaming, is this ok? [dune-xt-la](https://github.com/dune-community/dune-xt-la/pull/115) is updated accordingly, not sure where `Mkl::exp` is used...

**Comment by tobiasleibner** [comment]
Looks good to me, thanks for fixing! The ``exp`` is used in the momentmodel stuff in dune-gdt, I will update the PR there.

**Pull request merged**
