### PR TITLE
dailywork-ftschindler

### PR DESCRIPTION
**Pull request by ftalbrecht**
I found these changes lying around somewhere. In particular, this includes an update of how the `Configuration` parses the command line, that we talked about ages ago, @renemilk, and that I still preferr.

### CODE REVIEW

**Comment by ftalbrecht** [comment]
To be clear: I would like to have the syntactic sugar as in https://github.com/dune-community/dune-xt-common/pull/97/commits/2a2a2e384f64a09f9a1f2e14dfeabbf26971823e, which would make our programs behave much more like other unix programs...

**Comment by renemilk** [comment]
Yes, please revert to the old behaviour, if I don't actively select the new one. Thanks.

I don't recall talking about this, but yeah, named options are good. But haven't I've been using them already is what I'm asking: https://github.com/wwu-numerik/dune-multiscale-experiments/blob/master/speedup/supermuc/phase2.pure.tpl#L35

**Comment by renemilk** [comment]
So what's the reason to implement that change then?

**Comment by ftalbrecht** [comment]
I mainly wanted to have `--named=options` instead of `-named=options`^^

**Comment by renemilk** [comment]
:roll_eyes: 

Is using a single dash now an error? If I have to change my scripts because you want two dashes I'll have to roll my eyes even harder at you.

**Comment by TiKeil** [comment]
I just started to compile and run my tests on this state and no test is working anymore (runtime error). This is probably not supposed to be like that, is it? 

`terminate called after throwing an instance of 'Dune::XT::Common::Exceptions::configuration_error'
  what():  Exceptions::configuration_error
[read_command_line|/home/tikeil/dune-gdt-LOD/dune-xt-common/dune/xt/common/configuration.cc:244]
=> when trying to read from the command line (see below).`

**Comment by renemilk** [comment]
I guess that means yes :wink:

**Pull request merged**
